app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.upload_details, name='upload_details'),
    path('<int:detail_id>/', views.upload_file, name='upload_file'),
    path('history/', views.upload_history, name='upload_history'),
]

file_uploader/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('profile/', views.user_profile, name='profile'),
    path('uploads/', include('app.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


class UploadDetail(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class UploadFile(models.Model):
    file = models.FileField()
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    detail = models.ForeignKey(UploadDetail, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.file.url

app/forms.py
from django import forms
from .models import UploadFile


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ('file', )

app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import UploadDetail, UploadFile
from .forms import UploadFileForm


def home(request):
    details = UploadDetail.objects.order_by('-id')
    return render(request, 'home.html', context={
        'details': details,
    })

def user_profile(request):
    details = UploadDetail.objects.order_by('-id')
    return render(request, 'user_profile.html', context={
        'details': details,
    })

# app
def upload_details(request):
    q = (
        "SELECT app_uploaddetail.*, app_uploadfile.file from app_uploaddetail "
        "LEFT OUTER JOIN app_uploadfile ON app_uploaddetail.id = app_uploadfile.detail_id "
        "AND app_uploadfile.user_id = %s "
        "GROUP BY app_uploaddetail.id"
    )
    details = UploadDetail.objects.raw(q, [request.user.id])
    return render(request, 'upload_details.html', context={
        'details': details,
    })


def upload_file(request, detail_id):
    user_id = request.user.id

    details = UploadDetail.objects.order_by('-id')
    detail = UploadDetail.objects.get(id=detail_id)
    form = UploadFileForm()
    uploaded_files = UploadFile.objects.filter(
        detail_id=detail_id, user_id=user_id).order_by('-id')

    # POSTED
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user_id = user_id
            obj.detail_id = detail_id
            obj.save()
            return HttpResponseRedirect(reverse('home'))
        else:
            print('error')

    return render(request, 'upload_file.html', context={
        'details': details,
        'detail': detail,
        'form': form,
        'uploaded_files': uploaded_files,
    })


def upload_history(request):
    user_id = request.user.id

    details = UploadDetail.objects.order_by('-id')
    uploaded_files = UploadFile.objects.filter(user_id=user_id).order_by('-id')

    return render(request, 'upload_history.html', context={
        'details': details,
        'uploaded_files': uploaded_files,
    })

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}FILE UPLOADER</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script>{% block script %}{% endblock %}</script>
</head>

<body>
    <nav id="navbar" class="navbar is-spaced has-background-grey-dark">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item has-text-white has-text-centered title has-text-weight-bold" href="{% url 'home' %}">
                FILE UPLOADER
                </a>
            </div>
            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons"> 
                            <a
                            {% if user.is_authenticated %}
                            href="{% url 'logout' %}" class="button is-warning">
                                Logout
                            {% else %}
                            href="{% url 'login' %}" class="button is-primary">
                                Login
                            {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="columns has-background-dark" style="margin: 0;">
        {% block body %}{% endblock %}
    </div>
</body>

<footer class="footer has-background-grey-dark">
    <div class="content has-text-centered">
      <p>
        <strong>&copy; 2020 konekato</strong>
      </p>
      <p>
        <a href="https://github.com/konekato" class="has-text-dark" target="_blank" rel="noopener noreferrer"><span class="icon is-medium">
            <i class="fab fa-2x fa-github"></i>
        </span></a>
      </p>
    </div>
</footer>

</html>

templates/body_base.html
{% extends 'base.html' %}

{% block body %}
<aside class="column is-2 is-fullheight menu has-background-grey-dark">
    <ul class="menu-list">
        <li>
            <a class="has-text-white" href="{% url 'home' %}" onmouseout="this.style.background=''" onmouseover="this.style.background='grey'">
                Home
            </a>
        </li>
    </ul>
    <p class="menu-label has-text-warning">
        Upload
    </p>
    <ul class="menu-list">
        <li>
            <a class="has-text-white" href="{% url 'app:upload_details' %}" onmouseout="this.style.background=''" onmouseover="this.style.background='grey'">Uploads</a>
            <ul>
                {% for detail in details %}
                <li>
                    <a class="has-text-white" href="{% url 'app:upload_file' detail.id %}" onmouseout="this.style.background=''" onmouseover="this.style.background='grey'">
                        {{ detail.title }}
                    </a>
                </li>
                {% endfor %}
            </ul>
            <a class="has-text-white" href="{% url 'app:upload_history' %}" onmouseout="this.style.background=''" onmouseover="this.style.background='grey'">
                History
            </a>
        </li>
    </ul>
    <p class="menu-label has-text-warning">
        User
    </p>
    <ul class="menu-list">
        <li>
            <a class="has-text-white" href="{% url 'profile' %}" onmouseout="this.style.background=''" onmouseover="this.style.background='grey'">
                Profile
            </a>
        </li>
    </ul>
</aside>

<div class="column is-10 has-background-dark">
    <section class="section">
        <div class="container is-fluid">
            <h1 class="title is-1 has-text-white">
                {% block page_title %}{% endblock %}
            </h1>
            {% block inner_content %}{% endblock %}
        </div>
        {% block outer_content %}{% endblock %}
    </section>
</div>
{% endblock %}

templates/home.html
{% extends 'body_base.html' %}

{% block title %}Home{% endblock %}

{% block page_title %}Home{% endblock %}

{% block inner_content %}
<div class="notification">        
</div>
{% endblock %}

templates/upload_details.html
{% extends 'body_base.html' %}

{% block title %}Uploads{% endblock %}

{% block page_title %}Uploads{% endblock %}

{% block inner_content %}
<div class="columns">
    <div class="column is-full">    
        <table class="table is-hoverable">
            <tbody>
                {% for detail in details %}
                <tr>
                    <td>
                        {% if detail.file %}
                        <span class="icon is-medium has-text-info" data-tooltip="Already submitted">
                            <i class="fas fa-lg fa-check-circle"></i>
                        </span>
                        {% else %}
                        <span class="icon is-medium has-text-danger" data-tooltip="Not yet">
                            <i class="fas fa-lg fa-exclamation-circle"></i>
                        </span>
                        {% endif %}
                    </td>
                    <td>
                        <p class="has-text-weight-bold">
                            <a href="{% url 'app:upload_file' detail.id %}">
                                {{ detail.title|truncatechars:100 }}
                            </a>
                        </p>
                        <p class="is-size-7">
                            {{ detail.text|truncatechars:200 }}
                        </p>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/upload_file.html
{% extends 'body_base.html' %}

{% block title %}{{ detail.title }} | Upload{% endblock %}

{% block script %}
function check(){
    if(window.confirm('ファイルをアップロードします。')){
        return true;
    }else{
        return false;
    }
}
{% endblock %}

{% block page_title %}File Upload{% endblock %}

{% block inner_content %}
<div class="notification">
    <h2 class="title is-2">{{ detail.title }}</h2>
    <br>
    <h3 class="subtitle is-4">{{ detail.text }}</h3>
    
    {% if uploaded_files %}
    <div class="has-text-info">
        <span class="icon">
            <i class="fas fa-lg fa-check-circle"></i>
        </span>
        Already submitted
    </div>
    {% else %}
    <div class="has-text-danger">
        <span class="icon">
            <i class="fas fa-lg fa-exclamation-circle"></i>
        </span>
        Not yet
    </div>
    {% endif %}
</div>
<form action="" method="POST" enctype="multipart/form-data" onSubmit="return check()">
    {% csrf_token %}
    <p class="has-text-warning">{{ form.file }}</p>
    <br>
    <button type="submit" class="button is-light">Submit</button>
</form>
{% endblock %}
{% block outer_content %}
<hr>
<h3 class="subtitle has-text-white has-text-centered">提出履歴</h3>
{% if uploaded_files %}
<div class="columns">
    <div class="column is-one-fifth"></div>
    <div class="column is-three-fifths">
        <table class="table has-background-dark is-fullwidth">
            <thead>
                <tr>
                    <th class="has-text-white">ファイル名</th>
                    <th class="has-text-white">提出日時</th>
                </tr>
            </thead>
            <tbody>
                {% for uploaded in uploaded_files %}
                <tr>
                    <th class="has-text-white"><a href='{{uploaded.file.url}}' target="_blank" rel="noopener noreferrer" onmouseout="this.style.color=''" onmouseover="this.style.color='skyblue'">{{ uploaded.file }}</a></th>
                    <th class="has-text-white">{{ uploaded.created }}</th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

templates/upload_history.html
{% extends 'body_base.html' %}

{% block title %}History{% endblock %}

{% block page_title %}History{% endblock %}

{% block outer_content %}
<br>
    {% if uploaded_files %}
    <div class="columns">
        <div class="column is-1"></div>
        <div class="column is-10">
            <table class="table has-background-dark is-fullwidth">
                <thead>
                    <tr>
                        <th class="has-text-white">提出場所</th>
                        <th class="has-text-white">ファイル名</th>
                        <th class="has-text-white">提出日時</th>
                    </tr>
                </thead>
                <tbody>
                    {% for uploaded in uploaded_files %}
                    <tr>
                        <th class="has-text-white"><a href="{% url 'app:upload_file' uploaded.detail.id %}" onmouseout="this.style.color=''" onmouseover="this.style.color='skyblue'">{{ uploaded.detail.title }}</a></th>
                        <th class="has-text-white"><a href='{{uploaded.file.url}}' target="_blank" rel="noopener noreferrer" onmouseout="this.style.color=''" onmouseover="this.style.color='skyblue'">{{ uploaded.file }}</a></th>
                        <th class="has-text-white">{{ uploaded.created }}</th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/user_profile.html
{% extends 'body_base.html' %}